CLASS LHC_YNDBS_R_INTEGRATION_TYPE DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.

    METHODS GET_INSTANCE_AUTHORIZATIONS FOR INSTANCE AUTHORIZATION
      IMPORTING KEYS REQUEST REQUESTED_AUTHORIZATIONS FOR YNDBS_R_INTEGRATION_TYPE RESULT RESULT.

    METHODS GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
      IMPORTING REQUEST REQUESTED_AUTHORIZATIONS FOR YNDBS_R_INTEGRATION_TYPE RESULT RESULT.

ENDCLASS.

CLASS LHC_YNDBS_R_INTEGRATION_TYPE IMPLEMENTATION.

  METHOD GET_INSTANCE_AUTHORIZATIONS.
  ENDMETHOD.

  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.

ENDCLASS.

CLASS LSC_YNDBS_R_INTEGRATION_TYPE DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_SAVER.
  PROTECTED SECTION.

    METHODS ADJUST_NUMBERS REDEFINITION.

    METHODS CLEANUP_FINALIZE REDEFINITION.

ENDCLASS.

CLASS LSC_YNDBS_R_INTEGRATION_TYPE IMPLEMENTATION.

  METHOD ADJUST_NUMBERS.
    DATA: LC_HEAD_INTERVAL TYPE CL_NUMBERRANGE_OBJECTS=>NR_ATTRIBUTES-OBJECT VALUE 'YNDBS_INT'.

    IF MAPPED-YNDBS_R_INTEGRATION_TYPE IS NOT INITIAL.

      TRY.
          CL_NUMBERRANGE_RUNTIME=>NUMBER_GET( EXPORTING NR_RANGE_NR = '10'
                                                        OBJECT      = LC_HEAD_INTERVAL
                                              IMPORTING NUMBER      = DATA(LF_HEAD_ID)
                                                        RETURNCODE  = DATA(LF_RT) ).
        CATCH CX_NUMBER_RANGES.
          "handle exception
      ENDTRY.
      LOOP AT MAPPED-YNDBS_R_INTEGRATION_TYPE REFERENCE INTO DATA(MAP).
        MAP->INTEGRATIONID = LF_HEAD_ID.
      ENDLOOP.
    ENDIF.

  ENDMETHOD.

  METHOD CLEANUP_FINALIZE.
  ENDMETHOD.

ENDCLASS.