CLASS LHC_YNDBS_R_SERVICE_TYPE DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.

    METHODS GET_INSTANCE_AUTHORIZATIONS FOR INSTANCE AUTHORIZATION
      IMPORTING KEYS REQUEST REQUESTED_AUTHORIZATIONS FOR YNDBS_R_SERVICE_TYPE RESULT RESULT.

*    METHODS GET_GLOBAL_AUTHORIZATIONS  FOR YNDBS_R_SERVICE_TYPE RESULT RESULT.

ENDCLASS.

CLASS LHC_YNDBS_R_SERVICE_TYPE IMPLEMENTATION.

  METHOD GET_INSTANCE_AUTHORIZATIONS.
  ENDMETHOD.

*  METHOD GET_GLOBAL_AUTHORIZATIONS.
*  ENDMETHOD.

ENDCLASS.

CLASS LSC_YNDBS_R_SERVICE_TYPE DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_SAVER.
  PROTECTED SECTION.


    METHODS CLEANUP_FINALIZE REDEFINITION.

ENDCLASS.

CLASS LSC_YNDBS_R_SERVICE_TYPE IMPLEMENTATION.


  METHOD CLEANUP_FINALIZE.
  ENDMETHOD.

ENDCLASS.